default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Toru0424
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: first_app_development

test:
  <<: *default
  database: first_app_test
